{{- if .Values.runner.serviceAccount.create -}}
{{- range include "tf-controller.runner.allowedNamespaces" . | fromJsonArray }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tf-controller.runner.serviceAccountName" $ }}
  namespace: {{ . }}
  labels:
    {{- include "tf-controller.labels" $ | nindent 4 }}
  {{- with $.Values.runner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with $.Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tf-runner.cache-encryption
  namespace: {{ . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "tf-controller.runner.serviceAccountName" $ }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
